apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ting
resources:
- ../../base
patches:
- path: certificate-patch.yaml
- path: httproute-patch.yaml
- target:
    kind: ConfigMap
    name: ting-config
  patch: |
    - op: replace
      path: /data/base_url
      value: https://ting.frontstate.org
