"""baseline-v2-schools-surveys

Revision ID: 6d7670f9f395
Revises: 
Create Date: 2026-05-12 09:48:59.465448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d7670f9f395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletins',
    sa.Column('bulletin_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_by', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('bulletin_id')
    )
    op.create_table('proposals',
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposals_slug'), 'proposals', ['slug'], unique=True)
    op.create_table('schools',
    sa.Column('school_code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('school_code')
    )
    op.create_table('cohorts',
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('school_code', sa.String(length=3), nullable=False),
    sa.Column('batch_number', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['school_code'], ['schools.school_code'], ),
    sa.PrimaryKeyConstraint('cohort_id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('school_code', 'batch_number', name='uq_cohort_school_batch')
    )
    op.create_table('codes',
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('code_str', sa.String(length=40), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('advocate_grade', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ),
    sa.PrimaryKeyConstraint('code_id')
    )
    op.create_index(op.f('ix_codes_code_str'), 'codes', ['code_str'], unique=True)
    op.create_table('surveys',
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ),
    sa.PrimaryKeyConstraint('survey_id')
    )
    op.create_index(op.f('ix_surveys_slug'), 'surveys', ['slug'], unique=True)
    op.create_table('comments',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('author_code_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('metrics_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('code_id', sa.Uuid(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('pledges',
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('amount_dollars', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_per_week', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('code_id', 'proposal_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_slug'), 'questions', ['slug'], unique=True)
    op.create_table('summary_snapshots',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('cohort_id', sa.Uuid(), nullable=False),
    sa.Column('survey_id', sa.Uuid(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.cohort_id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.survey_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('cohort_id', 'survey_id', 'captured_at')
    )
    op.create_table('endorsements',
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.PrimaryKeyConstraint('code_id', 'comment_id')
    )
    op.create_table('responses',
    sa.Column('response_id', sa.Uuid(), nullable=False),
    sa.Column('code_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['code_id'], ['codes.code_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    sa.UniqueConstraint('code_id', 'question_id', name='uq_response_code_question')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responses')
    op.drop_table('endorsements')
    op.drop_table('summary_snapshots')
    op.drop_index(op.f('ix_questions_slug'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('pledges')
    op.drop_table('metrics_events')
    op.drop_table('comments')
    op.drop_index(op.f('ix_surveys_slug'), table_name='surveys')
    op.drop_table('surveys')
    op.drop_index(op.f('ix_codes_code_str'), table_name='codes')
    op.drop_table('codes')
    op.drop_table('cohorts')
    op.drop_table('schools')
    op.drop_index(op.f('ix_proposals_slug'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_table('bulletins')
    # ### end Alembic commands ###
